name: pr-check-validation

on:
  push:
    branches: [dev, main, master]
  pull_request:
    branches: [dev, main, master]

jobs:

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Format
        run: npm run format

      - name: Run ESLint
        run: npm run lint

  build:
    name: Validation build project
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verify build
        run: |
          if [ -d "dist" ]; then
            echo "✅ Success build"
          else
            echo "❌ Build failed"
            exit 1
          fi
